In [78]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [79]:
df = pd.read_csv("turboaz.csv")

In [80]:
df

Unnamed: 0 Şəhər       Marka     Model  Buraxılış ili         Ban növü  \
0               0  Bakı  Land Rover  RR Sport           2015  Offroader / SUV   
1               1  Bakı      Nissan     Tiida           2012          Hetçbek   
2               2  Bakı    Mercedes  G 63 AMG           2018  Offroader / SUV   
3               3  Bakı       Isuzu  NPR75L-K           2022       Yük maşını   
4               4  Bakı        Ford   Transit           2007       Yük maşını   
...           ...   ...         ...       ...            ...              ...   
10791       10791  Bakı    Mercedes     E 250           2012            Sedan   
10792       10792  Bakı         BMW        X5           2016  Offroader / SUV   
10793       10793  Bakı      Toyota     Prius           2011          Liftbek   
10794       10794  Bakı        Opel     Astra           2005          Hetçbek   
10795       10795  Bakı  LADA (VAZ)      2107           2007            Sedan   

               Rəng               Mühərrik       Yürüş Sürətlər qutusu  \
0                Ağ  5.0 L/510 a.g./Benzin   39 800 km         Avtomat   
1              Qara  1.5 L/109 a.g./Benzin   48 000 km         Avtomat   
2               Göy  4.0 L/585 a.g./Benzin   50 000 km         Avtomat   
3                Ağ   5.2 L/150 a.g./Dizel        0 km        Mexaniki   
4                Ağ   2.4 L/140 a.g./Dizel  270 000 km        Mexaniki   
...             ...                    ...         ...             ...   
10791            Ağ  1.8 L/204 a.g./Benzin  130 000 km         Avtomat   
10792          Qara  3.0 L/306 a.g./Benzin  142 000 km         Avtomat   
10793            Ağ   1.8 L/99 a.g./Hibrid  396 373 km        Variator   
10794        Gümüşü   1.4 L/90 a.g./Benzin  157 000 km        Mexaniki   
10795  Tünd qırmızı   1.6 L/75 a.g./Benzin   88 556 km        Mexaniki   

      Ötürücü  Yeni                    Vəziyyəti Hansı bazar üçün yığılıb  \
0         Tam  Xeyr  Vuruğu yoxdur, rənglənməyib              Rəsmi diler   
1          Ön  Xeyr  Vuruğu yoxdur, rənglənməyib                 Yaponiya   
2         Tam  Xeyr  Vuruğu yoxdur, rənglənməyib              Rəsmi diler   
3        Arxa  Bəli  Vuruğu yoxdur, rənglənməyib                      NaN   
4        Arxa  Xeyr  Vuruğu yoxdur, rənglənməyib                      NaN   
...       ...   ...                          ...                      ...   
10791    Arxa  Xeyr  Vuruğu yoxdur, rənglənməyib                      NaN   
10792     Tam  Xeyr  Vuruğu yoxdur, rənglənməyib                      NaN   
10793      Ön  Xeyr     Vuruğu yoxdur, rənglənib                  Amerika   
10794      Ön  Xeyr  Vuruğu yoxdur, rənglənməyib                   Avropa   
10795    Arxa  Xeyr  Vuruğu yoxdur, rənglənməyib                   Rusiya   

      Yerlərin sayı Sahiblər Qəzalı  
0               NaN      NaN    NaN  
1                 5        1    NaN  
2                 7        1    NaN  
3               NaN      NaN    NaN  
4               NaN      NaN    NaN  
...             ...      ...    ...  
10791           NaN      NaN    NaN  
10792             5        1    NaN  
10793             5        1    NaN  
10794             5        1    NaN  
10795           NaN      NaN    NaN  

[10796 rows x 17 columns]

In [81]:
type(df['Qəzalı'].loc[0])

float

In [82]:
df.isnull().sum()/len(df)*100

Unnamed: 0                   0.000000
Şəhər                        0.000000
Marka                        0.000000
Model                        0.000000
Buraxılış ili                0.000000
Ban növü                     0.000000
Rəng                         0.000000
Mühərrik                     0.000000
Yürüş                        0.000000
Sürətlər qutusu              0.000000
Ötürücü                      0.000000
Yeni                         0.000000
Vəziyyəti                    1.926639
Hansı bazar üçün yığılıb    37.449055
Yerlərin sayı               33.929233
Sahiblər                    40.987403
Qəzalı                      99.805484
dtype: float64

In [83]:
df = df.drop('Qəzalı',axis=1)

In [84]:
imputer = SimpleImputer(strategy="most_frequent")
imputer.fit_transform(df.select_dtypes(exclude="string"))

array([[0, 'Bakı', 'Land Rover', ..., 'Rəsmi diler', '5', '1'],
       [1, 'Bakı', 'Nissan', ..., 'Yaponiya', '5', '1'],
       [2, 'Bakı', 'Mercedes', ..., 'Rəsmi diler', '7', '1'],
       ...,
       [10793, 'Bakı', 'Toyota', ..., 'Amerika', '5', '1'],
       [10794, 'Bakı', 'Opel', ..., 'Avropa', '5', '1'],
       [10795, 'Bakı', 'LADA (VAZ)', ..., 'Rusiya', '5', '1']],
      dtype=object)

In [85]:
df['Vəziyyəti']=df['Vəziyyəti'].fillna(df['Vəziyyəti'].mode()[0])

In [86]:
df

Unnamed: 0 Şəhər       Marka     Model  Buraxılış ili         Ban növü  \
0               0  Bakı  Land Rover  RR Sport           2015  Offroader / SUV   
1               1  Bakı      Nissan     Tiida           2012          Hetçbek   
2               2  Bakı    Mercedes  G 63 AMG           2018  Offroader / SUV   
3               3  Bakı       Isuzu  NPR75L-K           2022       Yük maşını   
4               4  Bakı        Ford   Transit           2007       Yük maşını   
...           ...   ...         ...       ...            ...              ...   
10791       10791  Bakı    Mercedes     E 250           2012            Sedan   
10792       10792  Bakı         BMW        X5           2016  Offroader / SUV   
10793       10793  Bakı      Toyota     Prius           2011          Liftbek   
10794       10794  Bakı        Opel     Astra           2005          Hetçbek   
10795       10795  Bakı  LADA (VAZ)      2107           2007            Sedan   

               Rəng               Mühərrik       Yürüş Sürətlər qutusu  \
0                Ağ  5.0 L/510 a.g./Benzin   39 800 km         Avtomat   
1              Qara  1.5 L/109 a.g./Benzin   48 000 km         Avtomat   
2               Göy  4.0 L/585 a.g./Benzin   50 000 km         Avtomat   
3                Ağ   5.2 L/150 a.g./Dizel        0 km        Mexaniki   
4                Ağ   2.4 L/140 a.g./Dizel  270 000 km        Mexaniki   
...             ...                    ...         ...             ...   
10791            Ağ  1.8 L/204 a.g./Benzin  130 000 km         Avtomat   
10792          Qara  3.0 L/306 a.g./Benzin  142 000 km         Avtomat   
10793            Ağ   1.8 L/99 a.g./Hibrid  396 373 km        Variator   
10794        Gümüşü   1.4 L/90 a.g./Benzin  157 000 km        Mexaniki   
10795  Tünd qırmızı   1.6 L/75 a.g./Benzin   88 556 km        Mexaniki   

      Ötürücü  Yeni                    Vəziyyəti Hansı bazar üçün yığılıb  \
0         Tam  Xeyr  Vuruğu yoxdur, rənglənməyib              Rəsmi diler   
1          Ön  Xeyr  Vuruğu yoxdur, rənglənməyib                 Yaponiya   
2         Tam  Xeyr  Vuruğu yoxdur, rənglənməyib              Rəsmi diler   
3        Arxa  Bəli  Vuruğu yoxdur, rənglənməyib                      NaN   
4        Arxa  Xeyr  Vuruğu yoxdur, rənglənməyib                      NaN   
...       ...   ...                          ...                      ...   
10791    Arxa  Xeyr  Vuruğu yoxdur, rənglənməyib                      NaN   
10792     Tam  Xeyr  Vuruğu yoxdur, rənglənməyib                      NaN   
10793      Ön  Xeyr     Vuruğu yoxdur, rənglənib                  Amerika   
10794      Ön  Xeyr  Vuruğu yoxdur, rənglənməyib                   Avropa   
10795    Arxa  Xeyr  Vuruğu yoxdur, rənglənməyib                   Rusiya   

      Yerlərin sayı Sahiblər  
0               NaN      NaN  
1                 5        1  
2                 7        1  
3               NaN      NaN  
4               NaN      NaN  
...             ...      ...  
10791           NaN      NaN  
10792             5        1  
10793             5        1  
10794             5        1  
10795           NaN      NaN  

[10796 rows x 16 columns]

In [87]:
df.isnull().sum()/len(df)*100


Unnamed: 0                   0.000000
Şəhər                        0.000000
Marka                        0.000000
Model                        0.000000
Buraxılış ili                0.000000
Ban növü                     0.000000
Rəng                         0.000000
Mühərrik                     0.000000
Yürüş                        0.000000
Sürətlər qutusu              0.000000
Ötürücü                      0.000000
Yeni                         0.000000
Vəziyyəti                    0.000000
Hansı bazar üçün yığılıb    37.449055
Yerlərin sayı               33.929233
Sahiblər                    40.987403
dtype: float64

In [88]:

df["Hansı bazar üçün yığılıb"]=df["Hansı bazar üçün yığılıb"].fillna(df["Hansı bazar üçün yığılıb"].mode()[0])

In [89]:
df.isnull().sum()

Unnamed: 0                     0
Şəhər                          0
Marka                          0
Model                          0
Buraxılış ili                  0
Ban növü                       0
Rəng                           0
Mühərrik                       0
Yürüş                          0
Sürətlər qutusu                0
Ötürücü                        0
Yeni                           0
Vəziyyəti                      0
Hansı bazar üçün yığılıb       0
Yerlərin sayı               3663
Sahiblər                    4425
dtype: int64

In [90]:
df["Yerlərin sayı"].unique()

array([nan, '5', '7', '4', '6', '3', '2', '1', '8+'], dtype=object)

In [91]:
df["Yerlərin sayı"]=pd.to_numeric(df["Yerlərin sayı"],errors="coerce")


In [92]:
mean = int(df['Yerlərin sayı'].mean())
mean


5

In [93]:

df['Yerlərin sayı'].fillna(mean, inplace=True)


In [94]:
df["Sahiblər"].unique()

array([nan, '1', '2', '0', '3', '4 və daha çox'], dtype=object)

In [95]:
df["Sahiblər"] =pd.to_numeric(df["Sahiblər"],errors="coerce")

In [96]:
median = df["Sahiblər"].median()

In [97]:
df['Sahiblər'].fillna(median, inplace=True)

In [98]:
df.isnull().sum()

Unnamed: 0                  0
Şəhər                       0
Marka                       0
Model                       0
Buraxılış ili               0
Ban növü                    0
Rəng                        0
Mühərrik                    0
Yürüş                       0
Sürətlər qutusu             0
Ötürücü                     0
Yeni                        0
Vəziyyəti                   0
Hansı bazar üçün yığılıb    0
Yerlərin sayı               0
Sahiblər                    0
dtype: int64

In [99]:
df2 = df["Mühərrik"].str.split("/",expand=True)

In [102]:
df = pd.concat([df,df2],axis=1)

KeyError: "['Mühərrik'] not found in axis"

Unnamed: 0 Şəhər       Marka     Model  Buraxılış ili         Ban növü  \
0               0  Bakı  Land Rover  RR Sport           2015  Offroader / SUV   
1               1  Bakı      Nissan     Tiida           2012          Hetçbek   
2               2  Bakı    Mercedes  G 63 AMG           2018  Offroader / SUV   
3               3  Bakı       Isuzu  NPR75L-K           2022       Yük maşını   
4               4  Bakı        Ford   Transit           2007       Yük maşını   
...           ...   ...         ...       ...            ...              ...   
10791       10791  Bakı    Mercedes     E 250           2012            Sedan   
10792       10792  Bakı         BMW        X5           2016  Offroader / SUV   
10793       10793  Bakı      Toyota     Prius           2011          Liftbek   
10794       10794  Bakı        Opel     Astra           2005          Hetçbek   
10795       10795  Bakı  LADA (VAZ)      2107           2007            Sedan   

               Rəng       Yürüş Sürətlər qutusu Ötürücü  Yeni  \
0                Ağ   39 800 km         Avtomat     Tam  Xeyr   
1              Qara   48 000 km         Avtomat      Ön  Xeyr   
2               Göy   50 000 km         Avtomat     Tam  Xeyr   
3                Ağ        0 km        Mexaniki    Arxa  Bəli   
4                Ağ  270 000 km        Mexaniki    Arxa  Xeyr   
...             ...         ...             ...     ...   ...   
10791            Ağ  130 000 km         Avtomat    Arxa  Xeyr   
10792          Qara  142 000 km         Avtomat     Tam  Xeyr   
10793            Ağ  396 373 km        Variator      Ön  Xeyr   
10794        Gümüşü  157 000 km        Mexaniki      Ön  Xeyr   
10795  Tünd qırmızı   88 556 km        Mexaniki    Arxa  Xeyr   

                         Vəziyyəti Hansı bazar üçün yığılıb  Yerlərin sayı  \
0      Vuruğu yoxdur, rənglənməyib              Rəsmi diler            5.0   
1      Vuruğu yoxdur, rənglənməyib                 Yaponiya            5.0   
2      Vuruğu yoxdur, rənglənməyib              Rəsmi diler            7.0   
3      Vuruğu yoxdur, rənglənməyib                   Avropa            5.0   
4      Vuruğu yoxdur, rənglənməyib                   Avropa            5.0   
...                            ...                      ...            ...   
10791  Vuruğu yoxdur, rənglənməyib                   Avropa            5.0   
10792  Vuruğu yoxdur, rənglənməyib                   Avropa            5.0   
10793     Vuruğu yoxdur, rənglənib                  Amerika            5.0   
10794  Vuruğu yoxdur, rənglənməyib                   Avropa            5.0   
10795  Vuruğu yoxdur, rənglənməyib                   Rusiya            5.0   

       Sahiblər      0         1       2  
0           1.0  5.0 L  510 a.g.  Benzin  
1           1.0  1.5 L  109 a.g.  Benzin  
2           1.0  4.0 L  585 a.g.  Benzin  
3           1.0  5.2 L  150 a.g.   Dizel  
4           1.0  2.4 L  140 a.g.   Dizel  
...         ...    ...       ...     ...  
10791       1.0  1.8 L  204 a.g.  Benzin  
10792       1.0  3.0 L  306 a.g.  Benzin  
10793       1.0  1.8 L   99 a.g.  Hibrid  
10794       1.0  1.4 L   90 a.g.  Benzin  
10795       1.0  1.6 L   75 a.g.  Benzin  

[10796 rows x 18 columns]